### ISSUE TITLE
count: n instruction not enforced

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/dockerfile_lint#13]
In sample_rules.yaml it appears the `count: 1` instruction is not used. For example, changing count to 2 doesn't impact the test.

```
    - 
      instruction: "USER"
      count: 2
      level: "warn"
      message: "No 'USER' instruction"
      description: "The process(es) within the container may run as root and RUN instructions my be run as root"
      reference_url: 
        - "https://docs.docker.com/reference/builder/"
        - "#user"
```
